set vb t_vb=\|40f
set columns=160
set lines=60
set guioptions=!aegmt

set guifont=LiterationMono_NF:h14:cANSI:qDRAFT

set guicursor=n-v-c:block-Cursor/lCursor-blinkon0
set guicursor+=o:hor50-Cursor-blinkon0
set guicursor+=i-ci:ver25-Cursor/lCursor-blinkon0
set guicursor+=r-cr:hor20-Cursor/lCursor-blinkon0
